#define LOG_LEVEL 2
#include "ctarget.h"
#define NUMBER_OF_FEDERATES 1
#define TARGET_FILES_DIRECTORY "/home/lfvmu/lf_flexpret/lf/Time/src-gen/Time"
#include "core/reactor.c"
#include "core/mixed_radix.h"

// FlexPRET
#include <stdint.h>
#include "tinyalloc.h"
#include <flexpret_io.h>

// Code generated by the Lingua Franca compiler from:
// file://home/lfvmu/lf_flexpret/lf/Time/Time.lf
int main(int argc, char* argv[]) {
    // FlexPRET
    _fp_print(111111);
    extern char end; // Set by linker.
    // Allocate 128 bits (16 bytes) for the heap.
    // ta_init(&end, &end+4*16003, 2500, 4, 4);
    // ta_init(&end, &end+4*19, 4, 4, 4);
    // FIXME: How to make sure that this is not overlapped with stack?
    //        Might need to move stack to the top.
    ta_init(&end, (const void*)(0x20000000+0x1F400), 128, 16, 4);

    lf_reactor_c_main(argc, argv);

    // FlexPRET
    // Terminate the simulation
    _fp_print(999999);
    _fp_finish();
    while(1) {}
    __builtin_unreachable();
}
// =============== START reactor class Source
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
} source_out_t;
typedef struct {
    struct self_base_t base;
    /*Correspondence: Range: [(5, 14), (5, 22)) -> Range: [(0, 0), (0, 8)) (src=/home/lfvmu/lf_flexpret/lf/Time/Time.lf)*/uint32_t v;
    source_out_t _lf_out;
    int _lf_out_width;
    reaction_t _lf__reaction_0;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
} source_self_t;
void sourcereaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    source_self_t* self = (source_self_t*)instance_args;
    ((self_base_t*)self)->executing_reaction = &self->_lf__reaction_0;
    source_out_t* out = &self->_lf_out;
    #pragma GCC diagnostic pop
    /*Correspondence: Range: [(9, 8), (10, 4)) -> Range: [(0, 0), (1, 4)) (src=/home/lfvmu/lf_flexpret/lf/Time/Time.lf)*/
    SET(out, self->v++);
        
}
source_self_t* new_Source() {
    source_self_t* self = (source_self_t*)_lf_new_reactor(sizeof(source_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = sourcereaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__t.last = NULL;
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class Source

// =============== START reactor class Sink
typedef struct {
    int value;
    bool is_present;
    int num_destinations;
} sink_in_t;
typedef struct {
    struct self_base_t base;
    sink_in_t* _lf_in;
    // width of -2 indicates that it is not a multiport.
    int _lf_in_width;
    // Default input (in case it does not get connected)
    sink_in_t _lf_default__in;
    reaction_t _lf__reaction_0;
    trigger_t _lf__in;
    reaction_t* _lf__in_reactions[1];
} sink_self_t;
void sinkreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    sink_self_t* self = (sink_self_t*)instance_args;
    ((self_base_t*)self)->executing_reaction = &self->_lf__reaction_0;
    sink_in_t* in = self->_lf_in;
    int in_width = self->_lf_in_width;
    #pragma GCC diagnostic pop
    /*Correspondence: Range: [(16, 8), (18, 4)) -> Range: [(0, 0), (2, 4)) (src=/home/lfvmu/lf_flexpret/lf/Time/Time.lf)*/// _fp_print(in->value);
    // Reaction Body
    _fp_print(in->value);
        
}
sink_self_t* new_Sink() {
    sink_self_t* self = (sink_self_t*)_lf_new_reactor(sizeof(sink_self_t));
    // Set input by default to an always absent default input.
    self->_lf_in = &self->_lf_default__in;
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = sinkreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__in.last = NULL;
    self->_lf__in_reactions[0] = &self->_lf__reaction_0;
    self->_lf__in.reactions = &self->_lf__in_reactions[0];
    self->_lf__in.number_of_reactions = 1;
    self->_lf__in.element_size = sizeof(int);
    return self;
}
// =============== END reactor class Sink

// =============== START reactor class Time
typedef struct {
    struct self_base_t base;
} time_self_t;
time_self_t* new_Time() {
    time_self_t* self = (time_self_t*)_lf_new_reactor(sizeof(time_self_t));
    return self;
}
// =============== END reactor class Time

char* _lf_default_argv[] = { "Time", "-o", "10", "sec" };
void _lf_set_default_command_line_options() {
    default_argc = 4;
    default_argv = _lf_default_argv;
}
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to reactions to be scheduled in _lf_trigger_startup_reactions().
reaction_t** _lf_startup_reactions = NULL;
int _lf_startup_reactions_size = 0;
// Empty array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
    return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    // Create the array that will contain pointers to is_present fields to reset on each step.
    _lf_is_present_fields_size = 1;
    _lf_is_present_fields = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields == NULL) error_print_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated = (bool**)calloc(1, sizeof(bool*));
    if (_lf_is_present_fields_abbreviated == NULL) error_print_and_exit("Out of memory!");
    _lf_is_present_fields_abbreviated_size = 0;
    
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    time_self_t* time_self[1];
    source_self_t* time_source_self[1];
    sink_self_t* time_sink_self[1];
    // ***** Start initializing Time of class Time
    time_self[0] = new_Time();
    {
        // ***** Start initializing Time.source of class Source
        time_source_self[0] = new_Source();
        // width of -2 indicates that it is not a multiport.
        time_source_self[0]->_lf_out_width = -2;
        { // For scoping
            static /*Correspondence: Range: [(5, 14), (5, 22)) -> Range: [(0, 0), (0, 8)) (src=/home/lfvmu/lf_flexpret/lf/Time/Time.lf)*/uint32_t _initial = 0;
            time_source_self[0]->v = _initial;
        } // End scoping.
        // Initializing timer Time.source.t.
        time_source_self[0]->_lf__t.offset = 0;
        time_source_self[0]->_lf__t.period = SEC(1);
        _lf_timer_triggers[_lf_timer_triggers_count++] = &time_source_self[0]->_lf__t;
        //***** End initializing Time.source
    }
    {
        // ***** Start initializing Time.sink of class Sink
        time_sink_self[0] = new_Sink();
        // width of -2 indicates that it is not a multiport.
        time_sink_self[0]->_lf_in_width = -2;
        //***** End initializing Time.sink
    }
    //***** End initializing Time
    
    // **** Start deferred initialize for Time
    {
        // **** Start deferred initialize for Time.source
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Time.source.
            time_source_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            time_source_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &time_source_self[0]->base.allocations); 
            time_source_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &time_source_self[0]->base.allocations); 
            time_source_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &time_source_self[0]->base.allocations); 
            {
                int count = 0;
                {
                    time_source_self[0]->_lf__reaction_0.output_produced[count++]
                    = &time_source_self[0]->_lf_out.is_present;
                }
            }
            // ** End initialization for reaction 0 of Time.source
        }
        // **** End of deferred initialize for Time.source
        // **** Start deferred initialize for Time.sink
        {
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_0 of Time.sink.
            time_sink_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0;
            }
            // ** End initialization for reaction 0 of Time.sink
        }
        // **** End of deferred initialize for Time.sink
    }
    // **** End of deferred initialize for Time
    // **** Start non-nested deferred initialize for Time
    // **** Start non-nested deferred initialize for Time.source
    // For reference counting, set num_destinations for port Time.source.out.
    // Iterate over range Time.source.out(0,1)->[Time.sink.in(0,1)].
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        int range_count = 0;
        time_source_self[src_runtime]->_lf_out.num_destinations = 1;
    }
    {
        int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
        // Iterate over range Time.source.out(0,1)->[Time.sink.in(0,1)].
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            int range_count = 0;
            // Reaction 0 of Time.source triggers 1 downstream reactions
            // through port Time.source.out.
            time_source_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
            // For reaction 0 of Time.source, allocate an
            // array of trigger pointers for downstream reactions through port Time.source.out
            trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                    1, sizeof(trigger_t*),
                    &time_source_self[src_runtime]->base.allocations); 
            time_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
        }
        for (int i = 0; i < 1; i++) triggers_index[i] = 0;
        // Iterate over ranges Time.source.out(0,1)->[Time.sink.in(0,1)] and Time.sink.in(0,1).
        {
            int src_runtime = 0; // Runtime index.
            int src_channel = 0; // Channel index.
            int src_bank = 0; // Bank index.
            // Iterate over range Time.sink.in(0,1).
            {
                int dst_runtime = 0; // Runtime index.
                int dst_channel = 0; // Channel index.
                int dst_bank = 0; // Bank index.
                int range_count = 0;
                // Point to destination port Time.sink.in's trigger struct.
                time_source_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &time_sink_self[dst_runtime]->_lf__in;
            }
        }
    }
    // Time.source.reaction_0 dominating upstream reaction.
    time_source_self[0]->_lf__reaction_0.last_enabling_reaction = NULL;
    // **** End of non-nested deferred initialize for Time.source
    // **** Start non-nested deferred initialize for Time.sink
    // Time.sink.reaction_0 dominating upstream reaction.
    time_sink_self[0]->_lf__reaction_0.last_enabling_reaction = &(time_source_self[0]->_lf__reaction_0);
    // **** End of non-nested deferred initialize for Time.sink
    // **** End of non-nested deferred initialize for Time
    // Connect inputs and outputs for reactor Time.
    // Connect inputs and outputs for reactor Time.source.
    // Connect Time.source.out(0,1)->[Time.sink.in(0,1)] to port Time.sink.in(0,1)
    // Iterate over ranges Time.source.out(0,1)->[Time.sink.in(0,1)] and Time.sink.in(0,1).
    {
        int src_runtime = 0; // Runtime index.
        int src_channel = 0; // Channel index.
        int src_bank = 0; // Bank index.
        // Iterate over range Time.sink.in(0,1).
        {
            int dst_runtime = 0; // Runtime index.
            int dst_channel = 0; // Channel index.
            int dst_bank = 0; // Bank index.
            int range_count = 0;
            time_sink_self[dst_runtime]->_lf_in = (sink_in_t*)&time_source_self[src_runtime]->_lf_out;
        }
    }
    // Connect inputs and outputs for reactor Time.sink.
    {
    }
    {
    }
    {
        int count = 0;
        {
            // Add port Time.source.out to array of is_present fields.
            _lf_is_present_fields[0 + count] = &time_source_self[0]->_lf_out.is_present;
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance Time
    {
        
        // Set reaction priorities for ReactorInstance Time.source
        {
            time_source_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 140737488355327 shifted left 16 bits.
            time_source_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
        }
        
        
        // Set reaction priorities for ReactorInstance Time.sink
        {
            time_sink_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 140737488355327 shifted left 16 bits.
            time_sink_self[0]->_lf__reaction_0.index = 0x7fffffffffff0001LL;
        }
        
    }
    
}
void _lf_trigger_startup_reactions() {
}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool _lf_trigger_shutdown_reactions() {                          
    for (int i = 0; i < _lf_shutdown_reactions_size; i++) {
        if (_lf_shutdown_reactions[i] != NULL) {
            _lf_enqueue_reaction(_lf_shutdown_reactions[i]);
        }
    }
    // Return true if there are shutdown reactions.
    return (_lf_shutdown_reactions_size > 0);
}
void terminate_execution() {}
